{{- if and .Values.cockroachdb.tls.enabled .Values.cockroachdb.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cockroachdb.fullname" . }}-node
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.k8s.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  duration: {{ .Values.cockroachdb.tls.certManager.issuer.nodeCertDuration }}
  renewBefore: {{ .Values.cockroachdb.tls.certManager.issuer.nodeCertExpiryWindow }}
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: node
  subject:
    organizations:
      - Cockroach
  dnsNames:
    - "localhost"
    - "127.0.0.1"
    - {{ printf "%s-public" (include "cockroachdb.fullname" .) | quote }}
    - {{ printf "%s-public.%s" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-public.%s.svc.%s" (include "cockroachdb.fullname" .) .Release.Namespace .Values.cockroachdb.clusterDomain | quote }}
    - {{ printf "*.%s" (include "cockroachdb.fullname" .) | quote }}
    - {{ printf "*.%s.%s" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "*.%s.%s.svc.%s" (include "cockroachdb.fullname" .) .Release.Namespace .Values.cockroachdb.clusterDomain | quote }}
    - {{ printf "%s-join" (include "cockroachdb.fullname" .) | quote }}
    - {{ printf "%s-join.%s" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-join.%s.svc.%s" (include "cockroachdb.fullname" .) .Release.Namespace .Values.cockroachdb.clusterDomain | quote }}
  secretName: {{ .Values.cockroachdb.tls.certManager.nodeSecret }}
  issuerRef:
    name: {{ .Values.cockroachdb.tls.certManager.issuer.name }}
    kind: {{ .Values.cockroachdb.tls.certManager.issuer.kind }}
    group: {{ .Values.cockroachdb.tls.certManager.issuer.group }}
{{- end }}
