{{- if and .Values.cockroachdb.tls.enabled .Values.cockroachdb.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cockroachdb.fullname" . }}-root-client
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  duration: {{ .Values.cockroachdb.tls.certManager.issuer.clientCertDuration }}
  renewBefore: {{ .Values.cockroachdb.tls.certManager.issuer.clientCertExpiryWindow }}
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: root
  subject:
    organizations:
      - Cockroach
  secretName: {{ .Values.cockroachdb.tls.certManager.clientRootSecret }}
  issuerRef:
  {{- if .Values.tls.certManager.certManagerIssuer.isSelfSignedIssuer }}
    name: {{ template "cockroachdb.fullname" . }}-ca-issuer
    kind: Issuer
    group: cert-manager.io
  {{- else }}
    name: {{ .Values.tls.certManager.certManagerIssuer.name }}
    kind: {{ .Values.tls.certManager.certManagerIssuer.kind }}
    group: {{ .Values.tls.certManager.certManagerIssuer.group }}
  {{- end }}
{{- end }}
