{{- if and .Values.cockroachdb.tls.enabled (and .Values.cockroachdb.tls.selfSigner.enabled (not .Values.cockroachdb.tls.selfSigner.caProvided)) }}
  {{- if .Values.cockroachdb.tls.selfSigner.rotateCerts }}
    {{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
    {{- else }}
apiVersion: batch/v1beta1
    {{- end }}
kind: CronJob
metadata:
  name: {{ template "rotatecerts.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  schedule: {{ template "selfcerts.caRotateSchedule" . }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
        {{- with .Values.cockroachdb.tls.selfSigner.labels }}
          labels: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.cockroachdb.tls.selfSigner.annotations }}
          annotations: {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
        {{- if and .Values.cockroachdb.tls.enabled .Values.cockroachdb.tls.selfSigner.image.credentials }}
          imagePullSecrets:
            - name: {{ template "cockroachdb.fullname" . }}.init-certs.registry
        {{- end }}
          restartPolicy: Never
        {{- with .Values.cockroachdb.tls.selfSigner.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.cockroachdb.tls.selfSigner.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.cockroachdb.tls.selfSigner.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
        {{- end }}
          containers:
            - name: cert-rotate-job
              image: "{{ .Values.cockroachdb.tls.selfSigner.image.registry }}/{{ .Values.cockroachdb.tls.selfSigner.image.repository }}:{{ .Values.cockroachdb.tls.selfSigner.image.tag }}"
              imagePullPolicy: "{{ .Values.cockroachdb.tls.selfSigner.image.pullPolicy }}"
              args:
                - rotate
                - --ca
                - --ca-duration={{ .Values.cockroachdb.tls.selfSigner.caCertDuration }}
                - --ca-expiry={{ .Values.cockroachdb.tls.selfSigner.caCertExpiryWindow }}
                - --ca-cron={{ template "selfcerts.caRotateSchedule" . }}
                - --readiness-wait={{ .Values.cockroachdb.tls.selfSigner.readinessWait }}
                - --pod-update-timeout={{ .Values.cockroachdb.tls.selfSigner.podUpdateTimeout }}
              env:
                - name: STATEFULSET_NAME
                  value: {{ template "cockroachdb.fullname" . }}
                - name: NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: CLUSTER_DOMAIN
                  value: {{ .Values.cockroachdb.clusterDomain}}
          serviceAccountName: {{ template "rotatecerts.fullname" . }}
  {{- end }}
{{- end }}
