# This Service is meant to be used by clients of the database.
# It exposes a ClusterIP that will automatically load balance connections
# to the different database Pods.
kind: Service
apiVersion: v1
metadata:
  name: {{ template "cockroachdb.fullname" . }}-public
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.cockroachdb.crdbCluster.service.public.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.k8s.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.cockroachdb.crdbCluster.service.public.annotations .Values.cockroachdb.tls.enabled }}
  annotations:
  {{- with .Values.cockroachdb.crdbCluster.service.public.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.cockroachdb.tls.enabled }}
    service.alpha.kubernetes.io/app-protocols: '{"http":"HTTPS"}'
  {{- end }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  {{- with .Values.cockroachdb.crdbCluster.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Cockroach Cloud operator doesn't provide a way to change the sql,grpc and http ports for the pods. Hence, making these
  # ports static here.
  type: {{ .Values.cockroachdb.crdbCluster.service.public.type | quote }}
  ports:
  {{- $ports := .Values.cockroachdb.crdbCluster.service.ports }}
    # The main port, served by gRPC, serves Postgres-flavor SQL, inter-node
    # traffic and the CLI.
    - name: {{ $ports.grpc.name | quote }}
      port: {{ $ports.grpc.port | int64 }}
      targetPort: grpc
    - name: {{ $ports.sql.name | quote }}
      port: {{ $ports.sql.port | int64 }}
      targetPort: sql
    # The secondary port serves the UI as well as health and debug endpoints.
    - name: {{ $ports.http.name | quote }}
      port: {{ $ports.http.port | int64 }}
      targetPort: http
