{{- if and .Values.tls.enabled .Values.tls.certs.certManager }}
{{- if .Values.tls.certs.useCertManagerV1CRDs }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Certificate
metadata:
  name: {{ template "cockroachdb.fullname" . }}-root-client
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  duration: 672h
  renewBefore: 48h
  usages:
    - digital signature
    - key encipherment
    - client auth
{{- if .Values.tls.certs.useCertManagerV1CRDs }}
  privateKey:
    algorithm: RSA
    size: 2048
{{- else }}
  keySize: 2048
  keyAlgorithm: rsa
{{- end }}
  commonName: root
{{- if .Values.tls.certs.useCertManagerV1CRDs }}
  subject:
    organizations:
      - Cockroach
{{- else }}
  organization:
    - Cockroach
{{- end }}
  secretName: {{ .Values.tls.certs.clientRootSecret }}
  issuerRef: {{- toYaml .Values.tls.certs.certManagerIssuer | nindent 4 }}
{{- end }}
