{{- if .Values.operator.enabled }}
---
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    {{- with .Values.statefulset.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.operator.tlsEnabled }}
  tlsEnabled: {{ .Values.operator.tlsEnabled }}
  {{- end }}
  {{- with .Values.operator.clusterSettings }}
  clusterSettings: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.regions }}
  regions: {{- toYaml . | nindent 4 }}
  {{- end }}
  features:
    - reconcile
    - reconcile-beta
  template:
    spec:
      image: "{{ .Values.operator.image.name }}"
      certificates:
        externalCertificates:
          {{- /* Note: defaults should match secrets and configmaps created by the self-signer job. */}}
          {{- if (eq (include "externalCertificates.isEmpty" .) "true") }}
            caConfigMapName: {{ printf "%s-ca-secret-crt" (include "cockroachdb.fullname" .) }}
            nodeSecretName: {{ printf "%s-node-secret" (include "cockroachdb.fullname" .) }}
            rootSqlClientSecretName: {{ printf "%s-client-secret" (include "cockroachdb.fullname" .) }}
            nodeCaConfigMapName: {{ printf "%s-ca-secret-crt" (include "cockroachdb.fullname" .) }}
            httpSecretName: {{ printf "%s-client-secret" (include "cockroachdb.fullname" .) }}
            nodeClientSecretName: {{ printf "%s-client-secret" (include "cockroachdb.fullname" .) }}
          {{- else }}
          caConfigMapName: {{ .Values.operator.certificates.externalCertificates.clientCaConfigMapName }}
          nodeSecretName: {{ .Values.operator.certificates.externalCertificates.nodeSecretName }}
          rootSqlClientSecretName: {{ .Values.operator.certificates.externalCertificates.rootSqlClientSecretName }}
          nodeCaConfigMapName: {{ .Values.operator.certificates.externalCertificates.nodeCaConfigMapName }}
          httpSecretName: {{ .Values.operator.certificates.externalCertificates.httpSecretName }}
          nodeClientSecretName: {{ .Values.operator.certificates.externalCertificates.nodeClientSecretName }}
          {{- end }}
      {{- with .Values.operator.dataStore }}
      dataStore: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.ports }}
      ports: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.flags }}
      flags: {{- toYaml . | nindent 8 }}
      {{- end }}
      podLabels:
        app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        {{- with .Values.operator.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.operator.podAnnotations }}
      podAnnotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.podEnvVariables }}
      env: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.resources }}
      resourceRequirements: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.operator.rbac.serviceAccountName | default (include "cockroachdb.serviceAccount.name" .) }}
      {{- if .Values.operator.loggingConfigMapName }}
      loggingConfigMapName: {{ .Values.operator.loggingConfigMapName }}
      {{- else }}
      {{- if .Values.operator.loggingConf }}
      loggingConfigMapName: {{ .Release.Name }}-logging
      {{- end }}
      {{- end }}
  # All properties below are solely to pass validation. They aren't used by the
  # betaclusterctrl controller so the values don't matter so long as they're
  # valid.
  dataStore: {}
{{- end }}
