{{- if and .Values.tls.enabled .Values.tls.certs.selfSigner.enabled }}
{{- if not .Values.tls.certs.selfSigner.caProvided }}
# Add the empty secret to add the CA certificates by selfSigner utility. Empty secret is added in helm template because
# helm uninstall should cleanup this secret and no residue should be left in system by selfSigner utility.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cockroachdb.fullname" . }}-ca-cert
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
{{- end }}
{{- end }}
