{{- if .Values.init.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cockroachdb.fullname" . }}-init
type: Opaque
stringData:
  users:
    {{- range $user := .Values.init.database.users }}
    {{ $user.name }}_PASSWORD: {{ $user.password }}
    {{- end }}

  license: {{ .Values.init.database.license }}
{{- end }}