{{- if .Values.init.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cockroachdb.fullname" . }}-init
type: Opaque
stringData:
{{- range $user := .Values.init.database.users }}
  {{ $user.name }}-password: {{ $user.password }}
{{- end }}

{{- if and .Values.init.database .Values.init.database.license }}
  license: {{ .Values.init.database.license }}
{{- end }}
{{- end }}
