{{- if .Values.init.provisioning.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cockroachdb.fullname" . }}-init
type: Opaque
stringData:

{{- range $user := .Values.init.provisioning.users }}
{{- if $user.password }}
  {{ $user.name }}-password: {{ $user.password }}
{{- end }}
{{- end }}

{{- range $clusterSetting, $clusterSettingValue := .Values.init.provisioning.clusterSettings }}
  {{ $clusterSetting | replace "." "-" }}-cluster-setting: {{ $clusterSettingValue }}
{{- end }}

{{- end }}
