---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: ${CRDBCLUSTER}
    meta.helm.sh/release-namespace: ${NAMESPACE}
  labels:
    app: cockroachdb
    app.kubernetes.io/managed-by: Helm
  name: cockroachdb
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: ${CRDBCLUSTER}
    meta.helm.sh/release-namespace: ${NAMESPACE}
  labels:
    app: cockroachdb
  name: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: ${CRDBCLUSTER}
    meta.helm.sh/release-namespace: ${NAMESPACE}
  labels:
    app: cockroachdb
    app.kubernetes.io/managed-by: Helm
  name: cockroachdb
  namespace: ${NAMESPACE}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: ${CRDBCLUSTER}
    meta.helm.sh/release-namespace: ${NAMESPACE}
  labels:
    app: cockroachdb
    app.kubernetes.io/managed-by: Helm
  name: cockroachdb
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: ${CRDBCLUSTER}
    meta.helm.sh/release-namespace: ${NAMESPACE}
  labels:
    app: cockroachdb
    app.kubernetes.io/managed-by: Helm
  name: cockroachdb
  namespace: ${NAMESPACE}
