apiVersion: v1
name: cockroachdb
home: https://www.cockroachlabs.com
version: 5.2.0
appVersion: 20.2.8
description: CockroachDB is a scalable, survivable, strongly-consistent SQL database.
icon: https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/media/cockroach_db.png
sources:
- https://github.com/cockroachdb/cockroach
maintainers:
- name: cockroachlabs
  email: helm-charts@cockroachlabs.com
