{{- $operatorCerts := splitList "\n" (include "operator.certs" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: cockroach-operator-certs
  namespace: default   # Change the namespace if needed
type: Opaque
data:
  {{ index $operatorCerts 0 }}
  {{ index $operatorCerts 1 }}
  {{ index $operatorCerts 2 }}